import Head from "next/head";
import Image from "next/image";
import { up, down } from "styled-breakpoints";
import styled, { ThemeProvider } from "styled-components";
import { useBreakpoint } from "styled-breakpoints/react-styled";
import { useEffect, useState } from "react";
import FormitTest from "../components/FormitTest";

export default function Home() {
  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Test />
    </Wrapper>
  );
}

const Wrapper = styled.div``;

const Test = styled(FormitTest)`
  width: 100px;
  height: 100px;
  background-color: red;
`;
